// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBp6gT7UQjKQ2rYuWaP-VtO-Er7iuWWKE',
    appId: '1:249580711748:web:13dbf0bb7872c02b3d7111',
    messagingSenderId: '249580711748',
    projectId: 'schoolbridge-6df8d',
    authDomain: 'schoolbridge-6df8d.firebaseapp.com',
    storageBucket: 'schoolbridge-6df8d.appspot.com',
    measurementId: 'G-SPD6TLDREZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzqdeDQI29yF7WLxbPkr3Wfniwq2uJnUY',
    appId: '1:249580711748:android:676a5fb7bf1a532c3d7111',
    messagingSenderId: '249580711748',
    projectId: 'schoolbridge-6df8d',
    storageBucket: 'schoolbridge-6df8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZ1bmnvrUQmR6FaLA6tTLTe5qS0-WHvw',
    appId: '1:249580711748:ios:2ac0043667761d1f3d7111',
    messagingSenderId: '249580711748',
    projectId: 'schoolbridge-6df8d',
    storageBucket: 'schoolbridge-6df8d.appspot.com',
    iosBundleId: 'com.example.schoolBridgeApp',
  );
}
